name: intelligent_image_analysis
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  path_provider: ^2.0.11
  hive: ^2.2.3
  bot_toast: ^4.0.3
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6+1
  image: ^4.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
